---
title: "hdda"
output: html_document
date: "2023-04-15"
---
```{r}
library(caret)
library(C50)
library(pROC)
library(randomUniformForest)
```


```{r}


data(carEvaluation)
```
```{r}
SEED<-0
```
```{r}
seed <- SEED
```

si esegue cross validation

```{r}
ctrl <- trainControl(method = "cv", 
                     classProbs = TRUE,
                     summaryFunction = multiClassSummary)
```

```{r}
set.seed(seed)
in_train <- createDataPartition(carEvaluation$class, p = 3/4, list = FALSE)
training <- carEvaluation[ in_train, ]
testing  <- carEvaluation[-in_train, ]
```

```{r}
mod <- train(class ~ ., data = training, 
             method = "C5.0",
             tuneGrid = data.frame(trials = c(1:20, 10*(3:10)),
                                   model = "rules",
                                   winnow = FALSE),
             metric = "logLoss",
             trControl = ctrl)
```
```{r}
test_pred <- predict(mod, testing, type = "prob")
test_pred$pred <- predict(mod, testing)
test_pred$obs <- testing$class

test_res <- multiClassSummary(test_pred, lev = levels(test_pred$obs))
test_res <- data.frame(t(test_res))
test_res$Data <- "Car Evaluation"
test_res$Model <- "Boosted C5.0 Rules"
test_res$Ordered <- "None"
test_res$Seed <- seed
test_res$Encoding <- "Dummy Variables"
test_res$Time <- mod$times$everything[3]
```
```{r}

```

```{r}
rs_res <- mod$resample
rs_res$Data <- "Car Evaluation"
rs_res$Model <- "Boosted C5.0 Rules"
rs_res$Ordered <- "None"
rs_res$Seed <- seed
rs_res$Encoding <- "Dummy Variables"
```
```{r}

```

```{r}
save(test_res, rs_res,
     file = file.path("./Users/danie","Results",
                      paste0("C5boostrules_dummy_", seed, ".RData")))
```


